# This is a basic workflow to help you get started with Actions
name: DAPP
on:
  workflow_dispatch:
    inputs:
      environment:
        description: '?DEV or ?STAGING or ?PROD'
        required: true
        default: 'STAGING'
      deployType:
        description: 'Type of Deployment - ?BUILD or ?DEPLOY or  ?BUILD+DEPLOY'
        required: true
        default: 'BUILD+DEPLOY'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: aws cli DEV
        uses: aws-actions/configure-aws-credentials@v1
        if: github.event.inputs.environment == 'DEV' || github.event.inputs.environment == 'STAGING'
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          name: id_rsa
          known_hosts: ${{ secrets.KNOWN_HOSTS }}

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - if: ${{github.event.inputs.environment == 'STAGING'}}
        name: DEV Build and upload to S3
        run: |
          branch_name=${GITHUB_REF#refs/heads/}
          if [ "${{ github.event.inputs.deployType}}" = "BUILD" ] || [ "${{ github.event.inputs.deployType}}" = "BUILD+DEPLOY" ]; then
            ls -ltr
          fi
      - name: rsync over ssh
        run: ./scripts/deploy_to_aws.sh